#!/usr/bin/env bash
# Team Brain — one-shot MEMBER setup
#
# Colleagues with an admin invite → member or viewer only.
# Admin runs team-brain-admin-setup.sh first — NOT this script.
#
# DEMO DEFAULTS (Brainstack Day 0 workshop only — change for your crew):
#   Epic: KAN-4 · Crew: Workshop Crew
#   Override: --jira YOUR-EPIC
#   Or env: TEAM_BRAIN_DEMO_JIRA_KEY, TEAM_BRAIN_DEMO_JIRA_SITE
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
API="$SCRIPT_DIR/team-brain-api.sh"
PUBLIC_ENV="${TEAM_BRAIN_PUBLIC_ENV:-$REPO_ROOT/supabase/project.public.env}"
PUBLIC_ENV_EXAMPLE="$REPO_ROOT/supabase/project.public.env.example"

# --- demo defaults (override for production crews) ---
DEFAULT_JIRA_KEY="${TEAM_BRAIN_DEMO_JIRA_KEY:-KAN-4}"
DEFAULT_JIRA_TITLE="${TEAM_BRAIN_DEMO_JIRA_TITLE:-Brainstack context layer — workshop spike}"
DEFAULT_JIRA_SITE="${TEAM_BRAIN_DEMO_JIRA_SITE:-https://brainstack-org.atlassian.net}"
DEFAULT_TEAM_NAME="${TEAM_BRAIN_DEMO_TEAM_NAME:-Workshop Crew}"
DEFAULT_ROLE="member"

INVITE="${TEAM_BRAIN_INVITE:-}"
DISPLAY_NAME="${TEAM_BRAIN_DISPLAY_NAME:-}"
SUPABASE_URL="${TEAM_BRAIN_SUPABASE_URL:-}"
ANON_KEY="${TEAM_BRAIN_SUPABASE_ANON_KEY:-}"
JIRA_KEY="$DEFAULT_JIRA_KEY"
JIRA_TITLE="$DEFAULT_JIRA_TITLE"
JIRA_SITE="$DEFAULT_JIRA_SITE"
ROLE="$DEFAULT_ROLE"
INTERACTIVE=1
SKIP_START=0
DRY_RUN=0

STEP=0
TOTAL_STEPS=7

die() { echo "error: $*" >&2; exit 1; }
info() { echo "→ $*" >&2; }
ok() { echo "✓ $*" >&2; }
step() {
  STEP=$((STEP + 1))
  echo "" >&2
  echo "[$STEP/$TOTAL_STEPS] $*" >&2
}

print_demo_notice() {
  cat >&2 <<EOF

──────────────────────────────────────────────────────────────────
 Demo defaults (workshop): epic ${JIRA_KEY} · crew "${DEFAULT_TEAM_NAME}"
 For your own crew, pass --jira YOUR-EPIC (must match admin's epic).
 See docs/workshop-brainstack-day0.md
──────────────────────────────────────────────────────────────────

EOF
}

usage() {
  cat <<EOF
Team Brain — one-shot MEMBER setup (not admin)

  bash core/scripts/team-brain-member-setup.sh [options]

Options:
  --invite, -i CODE       Invite from admin (required)
  --name, -n "Your Name"  Display name (unique on crew)
  --role ROLE             member (default) or viewer
  --url URL  --anon KEY   Supabase (or use project.public.env)
  --jira KEY              Default: $DEFAULT_JIRA_KEY (demo — use your epic)
  --non-interactive  --skip-start  --dry-run  -h

Admin? team-brain-admin-setup.sh first.
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --invite|-i) INVITE="${2:-}"; shift 2 ;;
    --name|-n) DISPLAY_NAME="${2:-}"; shift 2 ;;
    --role) ROLE="${2:-}"; shift 2 ;;
    --url) SUPABASE_URL="${2:-}"; shift 2 ;;
    --anon) ANON_KEY="${2:-}"; shift 2 ;;
    --jira) JIRA_KEY="${2:-}"; shift 2 ;;
    --non-interactive) INTERACTIVE=0; shift ;;
    --skip-start) SKIP_START=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
done

JIRA_KEY=$(echo "$JIRA_KEY" | tr '[:lower:]' '[:upper:]')
ROLE=$(echo "$ROLE" | tr '[:upper:]' '[:lower:]')
print_demo_notice

prompt() {
  local var_name="$1" prompt_text="$2" default="${3:-}" value=""
  [ "$INTERACTIVE" -eq 1 ] || return 1
  if [ -n "$default" ]; then
    read -r -p "$prompt_text [$default]: " value || true
    value="${value:-$default}"
  else
    read -r -p "$prompt_text: " value || true
  fi
  printf -v "$var_name" '%s' "$value"
}

is_placeholder() {
  case "${1:-}" in ""|*YOUR_PROJECT*|*your-project*|*example.supabase*) return 0 ;; esac
  case "${2:-}" in ""|your-anon-key|YOUR_ANON*|replace-me*|changeme*) return 0 ;; esac
  return 1
}

write_public_env() {
  mkdir -p "$(dirname "$PUBLIC_ENV")"
  cat >"$PUBLIC_ENV" <<EOF
# Generated by team-brain-member-setup.sh — gitignored; do not commit live keys.
TEAM_BRAIN_SUPABASE_URL=$1
TEAM_BRAIN_SUPABASE_ANON_KEY=$2
TEAM_BRAIN_JIRA_SITE=$JIRA_SITE
EOF
  chmod 600 "$PUBLIC_ENV" 2>/dev/null || true
  ok "Wrote $PUBLIC_ENV"
}

load_public_env_file() {
  [ -f "$PUBLIC_ENV" ] || return 0
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      TEAM_BRAIN_SUPABASE_URL=*) [ -n "$SUPABASE_URL" ] || SUPABASE_URL="${line#TEAM_BRAIN_SUPABASE_URL=}" ;;
      TEAM_BRAIN_SUPABASE_ANON_KEY=*) [ -n "$ANON_KEY" ] || ANON_KEY="${line#TEAM_BRAIN_SUPABASE_ANON_KEY=}" ;;
    esac
  done <"$PUBLIC_ENV"
}

write_demo_pin() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  jq -n \
    --arg team "$DEFAULT_TEAM_NAME" \
    --arg key "$JIRA_KEY" \
    --arg notes "Demo pin from member-setup. Replace default_jira_key with YOUR epic for non-demo crews." \
    '{version:1, team_name:$team, default_jira_key:$key, jira_keys:[$key], supabase_project_ref:null, notes:$notes}' \
    >"$path"
}

step "Checking dependencies"
need_cmd() { command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1"; }
need_cmd curl
need_cmd jq
[ -f "$API" ] || die "team-brain-api.sh not found at $API"
ok "curl, jq, team-brain-api.sh"

step "Validating Supabase config"
cd "$REPO_ROOT"
export TEAM_BRAIN_DIR="${TEAM_BRAIN_DIR:-$REPO_ROOT/.team-brain}"
load_public_env_file

if is_placeholder "$SUPABASE_URL" "$ANON_KEY" && [ "$INTERACTIVE" -eq 1 ]; then
  info "Ask admin for URL + anon from the share bundle."
  [ ! -f "$PUBLIC_ENV" ] && [ -f "$PUBLIC_ENV_EXAMPLE" ] && cp "$PUBLIC_ENV_EXAMPLE" "$PUBLIC_ENV"
  prompt SUPABASE_URL "Supabase project URL" ""
  prompt ANON_KEY "Supabase anon key" ""
fi

is_placeholder "$SUPABASE_URL" "$ANON_KEY" && \
  die "Supabase URL/anon missing. Set $PUBLIC_ENV or pass --url / --anon."

if [ "$DRY_RUN" -eq 0 ]; then write_public_env "$SUPABASE_URL" "$ANON_KEY"
else info "Dry run — would write $PUBLIC_ENV"; fi
export TEAM_BRAIN_SUPABASE_URL="$SUPABASE_URL"
export TEAM_BRAIN_SUPABASE_ANON_KEY="$ANON_KEY"
export TEAM_BRAIN_JIRA_SITE="$JIRA_SITE"
export TEAM_BRAIN_PUBLIC_ENV="$PUBLIC_ENV"
ok "Supabase configured"

step "Installing crew pin ($JIRA_KEY)"
PIN_PATH="$TEAM_BRAIN_DIR/project.json"
if [ "$DRY_RUN" -eq 1 ]; then
  info "Dry run — would write pin at $PIN_PATH"
elif [ ! -f "$PIN_PATH" ]; then
  write_demo_pin "$PIN_PATH"
  ok "Wrote demo pin ($JIRA_KEY)"
else
  ok "Pin exists: $PIN_PATH"
fi

step "Collecting join credentials"
[ -n "$INVITE" ] || prompt INVITE "Invite code from admin" "" || die "missing --invite"
[ -n "$DISPLAY_NAME" ] || prompt DISPLAY_NAME "Your display name" "" || die "missing --name"

case "$ROLE" in
  member|viewer) ;;
  admin) die "use team-brain-admin-setup.sh for admin" ;;
  *) die "role must be member or viewer" ;;
esac

if [ "$DRY_RUN" -eq 1 ]; then
  echo "Dry run: onboard → verify → start $JIRA_KEY"
  exit 0
fi

step "Joining crew (onboard)"
bash "$API" onboard "$INVITE" "$DISPLAY_NAME" "$JIRA_KEY" --role "$ROLE"
ok "Onboard complete"

step "Verifying connection"
bash "$API" whoami | jq '{display_name, role, team_name}'
bash "$API" pin show | jq '{default_jira_key: (.default_jira_key // .jira_key), team_name}' 2>/dev/null || true
bash "$API" status >/dev/null
ok "Verified"

if [ "$SKIP_START" -eq 0 ]; then
  step "Starting sync ($JIRA_KEY)"
  bash "$API" start "$JIRA_KEY"
  bash "$API" sync-status "$JIRA_KEY" | jq '{jira_key, mode}' 2>/dev/null || bash "$API" sync-status "$JIRA_KEY"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo " Member setup complete · epic $JIRA_KEY"
echo " Cursor: I'm starting on $JIRA_KEY — start Team Brain sync, summarize crew memory, then help me."
echo " (Demo defaults — pass --jira YOUR-EPIC for your own initiative.)"
echo "═══════════════════════════════════════════════════════════════"
